In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("eventos_espera_semana_hp.csv", delimiter=",")
df

,ICAO,llegada_punto,salida_punto,despegue,tiempo_espera,aircraft_type,llegada_lon,llegada_lat,salida_lon,salida_lat,holding_point,parado,runway,fecha_despegue,hora_despegue
0,39bdae,2024-12-07 10:01:23.317,2024-12-07 10:02:45.266,2024-12-07 10:02:46.296,82.979,Medium 2 (between 34000 kg to 136000 kg),-3.561209,40.499423,-3.559227,40.506278,Y1,False,18L/36R,2024-12-07,10
1,4d24f1,2024-12-01 16:33:52.843,2024-12-01 16:35:40.634,2024-12-01 16:35:43.103,110.260,Medium 2 (between 34000 kg to 136000 kg),-3.576221,40.491579,-3.574645,40.497584,Z2,False,18R/36L,2024-12-01,16
2,71c082,2024-12-07 20:53:30.784,2024-12-07 20:55:13.042,2024-12-07 20:55:13.148,102.364,Heavy (larger than 136000 kg),-3.576253,40.491532,-3.574631,40.496567,Z2,False,18R/36L,2024-12-07,20
3,06a140,2024-12-01 18:26:29.008,2024-12-01 18:27:27.916,2024-12-01 18:27:29.141,60.133,Heavy (larger than 136000 kg),-3.561240,40.499423,-3.559211,40.505358,Y1,False,18L/36R,2024-12-01,18
4,06a140,2024-12-02 16:23:27.259,2024-12-02 16:24:41.134,2024-12-02 16:24:43.186,75.927,Heavy (larger than 136000 kg),-3.561234,40.499428,-3.559196,40.504543,Y1,False,18L/36R,2024-12-02,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4000,347307,2024-12-07 14:38:54.942,2024-12-07 14:41:46.659,2024-12-07 14:41:47.136,172.194,Medium 2 (between 34000 kg to 136000 kg),-3.561203,40.499565,-3.559235,40.505859,Y1,True,18L/36R,2024-12-07,14
4001,4bb289,2024-12-01 14:12:43.985,2024-12-01 14:14:08.288,2024-12-01 14:14:08.764,84.779,Medium 2 (between 34000 kg to 136000 kg),-3.561225,40.499481,-3.559235,40.505894,Y1,False,18L/36R,2024-12-01,14
4002,4cae17,2024-12-02 05:03:38.741,2024-12-02 05:04:47.780,2024-12-02 05:04:48.984,70.243,Medium 2 (between 34000 kg to 136000 kg),-3.576253,40.491521,-3.574661,40.498764,Z2,False,18R/36L,2024-12-02,5
4003,4cae17,2024-12-06 11:07:15.791,2024-12-06 11:08:21.696,2024-12-06 11:08:22.179,66.388,Medium 2 (between 34000 kg to 136000 kg),-3.561218,40.501179,-3.559227,40.507418,Y3,False,18L/36R,2024-12-06,11
4004,4cae17,2024-12-07 11:23:43.279,2024-12-07 11:24:35.632,2024-12-07 11:24:36.451,53.172,Medium 2 (between 34000 kg to 136000 kg),-3.561203,40.499428,-3.559235,40.506844,Y1,False,18L/36R,2024-12-07,11

In [2]:
df["holding_point"] = df["holding_point"].astype(str)
df["runway"] = df["runway"].astype(str)

In [3]:
df.dtypes

ICAO               object
llegada_punto      object
salida_punto       object
despegue           object
tiempo_espera     float64
aircraft_type      object
llegada_lon       float64
llegada_lat       float64
salida_lon        float64
salida_lat        float64
holding_point      object
parado               bool
runway             object
fecha_despegue     object
hora_despegue       int64
dtype: object

In [4]:
df = df[df["runway"]!="nan"]

In [5]:
df[df["holding_point"] == "LE"]

,ICAO,llegada_punto,salida_punto,despegue,tiempo_espera,aircraft_type,llegada_lon,llegada_lat,salida_lon,salida_lat,holding_point,parado,runway,fecha_despegue,hora_despegue
353,347519,2024-12-02 12:24:06.964,2024-12-02 12:25:04.168,2024-12-02 12:25:05.919,58.955,Heavy (larger than 136000 kg),-3.574631,40.485752,-3.570999,40.479950,LE,False,14R/32L,2024-12-02,12
768,346456,2024-12-02 11:43:17.820,2024-12-02 11:48:57.674,2024-12-02 11:48:59.762,341.942,Heavy (larger than 136000 kg),-3.574458,40.485853,-3.572008,40.480942,LE,True,14R/32L,2024-12-02,11
787,347343,2024-12-02 11:57:12.939,2024-12-02 12:02:02.482,2024-12-02 12:02:02.997,290.058,Heavy (larger than 136000 kg),-3.574463,40.485855,-3.571182,40.480145,LE,True,14R/32L,2024-12-02,12
892,347259,2024-12-02 11:09:28.652,2024-12-02 11:11:00.189,2024-12-02 11:11:05.028,96.376,Heavy (larger than 136000 kg),-3.574524,40.485832,-3.571571,40.480534,LE,False,14R/32L,2024-12-02,11
894,347259,2024-12-04 07:01:39.363,2024-12-04 11:18:00.123,2024-12-04 11:19:31.610,15472.247,Heavy (larger than 136000 kg),-3.575119,40.485477,-3.572601,40.491852,LE,False,18R/36L,2024-12-04,11
990,4ca92d,2024-12-02 11:17:17.953,2024-12-02 11:20:08.841,2024-12-02 11:20:09.869,171.916,Medium 2 (between 34000 kg to 136000 kg),-3.574458,40.485864,-3.571727,40.480685,LE,False,14R/32L,2024-12-02,11
1036,3455d5,2024-12-02 11:33:42.184,2024-12-02 11:35:21.227,2024-12-02 11:35:21.639,99.455,Heavy (larger than 136000 kg),-3.574458,40.485864,-3.570755,40.479698,LE,False,14R/32L,2024-12-02,11
1159,34520f,2024-12-01 09:33:02.703,2024-12-01 11:27:10.992,2024-12-01 11:30:24.852,7042.149,Heavy (larger than 136000 kg),-3.575348,40.485283,-3.572461,40.490589,LE,False,18R/36L,2024-12-01,11
1236,aabf87,2024-12-02 10:39:38.147,2024-12-02 10:43:11.580,2024-12-02 10:43:12.611,214.464,Heavy (larger than 136000 kg),-3.574505,40.485829,-3.571196,40.480138,LE,True,14R/32L,2024-12-02,10
1269,4063de,2024-12-02 11:18:59.443,2024-12-02 11:30:54.226,2024-12-02 11:30:55.924,716.481,Medium 2 (between 34000 kg to 136000 kg),-3.574536,40.485923,-3.572617,40.481407,LE,True,14R/32L,2024-12-02,11
1617,3444c4,2024-12-02 11:53:31.841,2024-12-02 11:55:43.411,2024-12-02 11:55:46.712,134.871,Heavy (larger than 136000 kg),-3.574458,40.485853,-3.572189,40.481129,LE,True,14R/32L,2024-12-02,11
1667,343147,2024-12-02 12:14:23.496,2024-12-02 12:15:48.440,2024-12-02 12:15:50.816,87.320,Heavy (larger than 136000 kg),-3.574489,40.485864,-3.571571,40.480546,LE,False,14R/32L,2024-12-02,12
1705,34510a,2024-12-02 11:30:34.990,2024-12-02 11:33:47.748,2024-12-02 11:33:52.083,197.093,Heavy (larger than 136000 kg),-3.574552,40.485818,-3.571747,40.480728,LE,False,14R/32L,2024-12-02,11
1723,e8027a,2024-12-02 10:55:27.598,2024-12-02 11:00:00.107,2024-12-02 11:00:02.986,275.388,Heavy (larger than 136000 kg),-3.574458,40.485853,-3.571075,40.480019,LE,True,14R/32L,2024-12-02,11
1846,aa1a16,2024-12-02 12:02:30.009,2024-12-02 12:07:04.357,2024-12-02 12:07:04.868,274.859,Heavy (larger than 136000 kg),-3.574489,40.485841,-3.571118,40.480080,LE,True,14R/32L,2024-12-02,12
1915,aaf828,2024-12-02 09:53:01.520,2024-12-02 09:56:14.879,2024-12-02 09:56:21.074,199.554,Heavy (larger than 136000 kg),-3.574463,40.485855,-3.572944,40.481873,LE,False,14R/32L,2024-12-02,9
2140,ab10cb,2024-12-02 12:29:12.033,2024-12-02 12:30:19.519,2024-12-02 12:30:23.930,71.897,Heavy (larger than 136000 kg),-3.574505,40.485841,-3.571665,40.480639,LE,False,14R/32L,2024-12-02,12
2301,34659a,2024-12-02 12:32:10.361,2024-12-02 12:33:43.427,2024-12-02 12:33:45.215,94.854,Heavy (larger than 136000 kg),-3.574474,40.485853,-3.571743,40.480685,LE,False,14R/32L,2024-12-02,12
2347,c0611f,2024-12-02 11:37:47.521,2024-12-02 11:42:36.673,2024-12-02 11:42:38.739,291.218,Heavy (larger than 136000 kg),-3.574458,40.485864,-3.570084,40.479069,LE,True,14R/32L,2024-12-02,11
2368,34640e,2024-12-02 11:48:55.099,2024-12-02 11:50:26.952,2024-12-02 11:50:31.356,96.257,Heavy (larger than 136000 kg),-3.574458,40.485853,-3.572757,40.481675,LE,False,14R/32L,2024-12-02,11
2603,344304,2024-12-02 11:10:31.386,2024-12-02 11:12:59.767,2024-12-02 11:13:00.585,149.199,Heavy (larger than 136000 kg),-3.574474,40.485864,-3.570838,40.479801,LE,False,14R/32L,2024-12-02,11
2616,347387,2024-12-02 12:00:25.815,2024-12-02 12:04:29.248,2024-12-02 12:04:29.413,243.598,Heavy (larger than 136000 kg),-3.574463,40.485855,-3.570923,40.479870,LE,True,14R/32L,2024-12-02,12
2865,020105,2024-12-02 12:20:07.027,2024-12-02 12:22:09.145,2024-12-02 12:22:14.227,127.200,Medium 2 (between 34000 kg to 136000 kg),-3.574524,40.485821,-3.572663,40.481628,LE,False,14R/32L,2024-12-02,12
3040,342105,2024-12-02 11:03:11.289,2024-12-02 11:07:04.577,2024-12-02 11:07:06.444,235.155,Medium 2 (between 34000 kg to 136000 kg),-3.574493,40.485844,-3.572052,40.480980,LE,True,14R/32L,2024-12-02,11
3123,e8044b,2024-12-03 12:13:47.475,2024-12-03 22:45:32.081,2024-12-03 22:49:48.916,38161.441,Heavy (larger than 136000 kg),-3.575316,40.485317,-3.572476,40.490589,LE,False,18R/36L,2024-12-03,22
3406,343694,2024-12-02 10:38:13.491,2024-12-02 10:39:37.630,2024-12-02 10:39:39.068,85.577,Medium 2 (between 34000 kg to 136000 kg),-3.574509,40.485821,-3.571014,40.479950,LE,False,14R/32L,2024-12-02,10
3487,344502,2024-12-02 11:13:19.298,2024-12-02 11:17:23.313,2024-12-02 11:17:27.624,248.326,Heavy (larger than 136000 kg),-3.574458,40.485864,-3.572159,40.481106,LE,True,14R/32L,2024-12-02,11
3651,3474c8,2024-12-02 10:14:09.754,2024-12-02 10:18:22.879,2024-12-02 10:18:25.865,256.111,Heavy (larger than 136000 kg),-3.574458,40.485864,-3.571655,40.480602,LE,True,14R/32L,2024-12-02,10
3764,345597,2024-12-02 10:33:49.665,2024-12-02 10:35:59.304,2024-12-02 10:36:00.032,130.367,Medium 2 (between 34000 kg to 136000 kg),-3.574478,40.485844,-3.571321,40.480290,LE,False,14R/32L,2024-12-02,10

In [6]:
lista_tuplas = list(zip(df['holding_point'], df['runway']))
print(len(lista_tuplas))

3996

In [7]:
set_tuplas = set(zip(df['holding_point'], df['runway']))
print(len(set_tuplas))

31

In [8]:
set_tuplas

{('K1', '14L/32R'),
 ('K1', '18R/36L'),
 ('K2', '14L/32R'),
 ('K3', '18L/36R'),
 ('K3', '18R/36L'),
 ('KA6', '14R/32L'),
 ('KA6', '18L/36R'),
 ('KA6', '18R/36L'),
 ('KA8', '14R/32L'),
 ('KA8', '18L/36R'),
 ('KA8', '18R/36L'),
 ('L1', '18L/36R'),
 ('L1', '18R/36L'),
 ('LA', '14R/32L'),
 ('LA', '18L/36R'),
 ('LA', '18R/36L'),
 ('LB', '14R/32L'),
 ('LC', '14R/32L'),
 ('LD', '14R/32L'),
 ('LE', '14R/32L'),
 ('LE', '18R/36L'),
 ('LF', '18R/36L'),
 ('Y1', '18L/36R'),
 ('Y2', '18L/36R'),
 ('Y3', '18L/36R'),
 ('Z1', '18R/36L'),
 ('Z2', '14R/32L'),
 ('Z2', '18R/36L'),
 ('Z3', '18R/36L'),
 ('Z4', '18R/36L'),
 ('Z6', '18R/36L')}

In [9]:
lista_set = list(set_tuplas)

for elem in lista_set:
    if elem[0] == "LE":
        print(elem)

('LE', '18R/36L')
('LE', '14R/32L')

In [10]:
dict_final={}
a = sorted(lista_set, key=str)
for elem in a:
    if elem[0] not in dict_final.keys():
        dict_final[elem[0]] = set()
    dict_final[elem[0]].add(elem[1])

dict_final

{'K1': {'14L/32R', '18R/36L'},
 'K2': {'14L/32R'},
 'K3': {'18L/36R', '18R/36L'},
 'KA6': {'14R/32L', '18L/36R', '18R/36L'},
 'KA8': {'14R/32L', '18L/36R', '18R/36L'},
 'L1': {'18L/36R', '18R/36L'},
 'LA': {'14R/32L', '18L/36R', '18R/36L'},
 'LB': {'14R/32L'},
 'LC': {'14R/32L'},
 'LD': {'14R/32L'},
 'LE': {'14R/32L', '18R/36L'},
 'LF': {'18R/36L'},
 'Y1': {'18L/36R'},
 'Y2': {'18L/36R'},
 'Y3': {'18L/36R'},
 'Z1': {'18R/36L'},
 'Z2': {'14R/32L', '18R/36L'},
 'Z3': {'18R/36L'},
 'Z4': {'18R/36L'},
 'Z6': {'18R/36L'}}

In [11]:
b = set(list(zip(df["ICAO"], df["llegada_lat"], df['llegada_lon'], df['runway'], df["fecha_despegue"])))

In [12]:
colores = {
    '14L/32R': 'blue',
    '14R/32L': 'green',
    '18R/36L': 'red',
    '18L/36R': 'purple'
}

In [13]:
for bb in b:
    if bb[0] == "8940d5":
        print(bb)

('8940d5', 40.4994111141916, -3.561224503950639, '18L/36R', '2024-12-03')
('8940d5', 40.48353680109573, -3.5760185935280537, '18L/36R', '2024-12-03')

In [14]:
import folium

# Crear un mapa centrado en una ubicación específica
mapa = folium.Map(location=[40.49184637554621, -3.572616577148437], zoom_start=15)  # Madrid, España

# Lista de coordenadas (latitud, longitud)
# Añadir marcadores al mapa
for icao, lat, lon, runw, fe in b:
    print(lat, lon, runw, fe)
    folium.Marker([lat, lon],tooltip=f"ICAO: {icao}, Lat: {lat}, Lon: {lon}, Fecha: {fe}", icon=folium.Icon(color=colores[runw], icon="info-sign")).add_to(mapa)

# Guardar el mapa en un archivo HTML y mostrarlo
mapa.save("mapa.html")

40.49942779541016 -3.5612335205078125 18L/36R 2024-12-04
40.49184036254883 -3.572616577148437 18R/36L 2024-12-07
40.49943923950195 -3.5612335205078125 18L/36R 2024-12-06
40.49185180664063 -3.572616577148437 18R/36L 2024-12-06
40.49943439031051 -3.561208898370916 18L/36R 2024-12-04
40.49942779541016 -3.56121826171875 18L/36R 2024-12-03
40.49247483075675 -3.5765803943980825 18R/36L 2024-12-05
40.495547278452726 -3.560990420254794 14L/32R 2024-12-02
40.49942275225106 -3.5612401095303623 18L/36R 2024-12-03
40.49152050988149 -3.576252677223899 18R/36L 2024-12-05
40.49945068359375 -3.561187744140625 18L/36R 2024-12-05
40.49953079223633 -3.56121826171875 18L/36R 2024-12-05
40.49185180664063 -3.5764923095703125 18R/36L 2024-12-03
40.49249810687566 -3.57656478881836 18R/36L 2024-12-03
40.49151992797852 -3.5762481689453125 18R/36L 2024-12-01
40.49150887182204 -3.576252677223899 18R/36L 2024-12-06
40.49942779541016 -3.5611724853515625 18L/36R 2024-12-06
40.49152050988149 -3.576252677223899 18R/36L 2024-12-02
40.48575210571289 -3.5746307373046875 14R/32L 2024-12-02
40.49943923950195 -3.5611724853515625 18L/36R 2024-12-06
40.49152050988149 -3.576252677223899 18R/36L 2024-12-04
40.49251556396485 -3.5763702392578125 18R/36L 2024-12-06
40.49152050988149 -3.5762370716441763 18R/36L 2024-12-02
40.49251556396485 -3.57659912109375 18R/36L 2024-12-05
40.49174163301112 -3.576439944180575 18R/36L 2024-12-05
40.49941635131836 -3.5612335205078125 18L/36R 2024-12-02
40.49942275225106 -3.561208898370916 18L/36R 2024-12-03
40.49256793523239 -3.5766116055575283 18R/36L 2024-12-07
40.49944602836997 -3.561224503950639 18L/36R 2024-12-07
40.49942779541016 -3.5612335205078125 18L/36R 2024-12-03
40.49172592163086 -3.5764617919921875 18R/36L 2024-12-03
40.4903683419955 -3.5727102106267754 18R/36L 2024-12-06
40.491625252416576 -3.57620586048473 18R/36L 2024-12-03
40.4994111141916 -3.561224503950639 18L/36R 2024-12-07
40.49250411987305 -3.57647705078125 18R/36L 2024-12-07
40.49249267578125 -3.5766143798828125 18R/36L 2024-12-06
40.49150887182204 -3.57620586048473 18R/36L 2024-12-04
40.49250411987305 -3.5765838623046875 18R/36L 2024-12-06
40.49942779541016 -3.5611724853515625 18L/36R 2024-12-03
40.49247483075675 -3.576549183238636 18R/36L 2024-12-03
40.49037551879883 -3.5726318359375 18R/36L 2024-12-03
40.49151992797852 -3.576263427734375 18R/36L 2024-12-06
40.49058946512513 -3.5725385492498223 18R/36L 2024-12-07
40.49249267578125 -3.5765838623046875 18R/36L 2024-12-05
40.49942275225106 -3.5612401095303623 18L/36R 2024-12-05
40.49941635131836 -3.5611724853515625 18L/36R 2024-12-02
40.49150848388672 -3.5762481689453125 18R/36L 2024-12-06
40.49176025390625 -3.5764617919921875 18R/36L 2024-12-07
40.49184036254883 -3.5726470947265625 18R/36L 2024-12-03
40.49942275225106 -3.561224503950639 18L/36R 2024-12-02
40.49155542405985 -3.5762370716441763 18R/36L 2024-12-06
40.50030899047852 -3.5611724853515625 18L/36R 2024-12-02
40.50034215894796 -3.56117768721147 18L/36R 2024-12-03
40.4915885925293 -3.576324462890625 18R/36L 2024-12-05
40.49943923950195 -3.561187744140625 18L/36R 2024-12-07
40.491532147940944 -3.576252677223899 18R/36L 2024-12-02
40.49157870017876 -3.576221466064453 18R/36L 2024-12-03
40.49942275225106 -3.5612401095303623 18L/36R 2024-12-03
40.49057782706568 -3.572522943670099 18R/36L 2024-12-01
40.49942779541016 -3.5612030029296875 18L/36R 2024-12-02
40.49193948002185 -3.5726789994673296 18R/36L 2024-12-05
40.49185180664063 -3.5726470947265625 18R/36L 2024-12-05
40.49942779541016 -3.5612335205078125 18L/36R 2024-12-01
40.49437183444783 -3.559710762717507 14L/32R 2024-12-02
40.49177169799805 -3.576400756835937 18R/36L 2024-12-03
40.4994111141916 -3.5612401095303623 18L/36R 2024-12-07
40.49943439031051 -3.5612401095303623 18L/36R 2024-12-03
40.49248123168945 -3.5766143798828125 18R/36L 2024-12-02
40.49945068359375 -3.5612335205078125 18L/36R 2024-12-03
40.49941635131836 -3.5612335205078125 18L/36R 2024-12-03
40.49942275225106 -3.5612401095303623 18L/36R 2024-12-04
40.49249267578125 -3.57659912109375 18R/36L 2024-12-05
40.499473571777344 -3.56121826171875 18L/36R 2024-12-06
40.49152050988149 -3.576252677223899 18R/36L 2024-12-06
40.499473571777344 -3.56121826171875 18L/36R 2024-12-02
40.49942275225106 -3.561115264892578 18L/36R 2024-12-02
40.49433517456055 -3.559783935546875 14L/32R 2024-12-02
40.49943923950195 -3.56121826171875 18L/36R 2024-12-02
40.48390921899828 -3.577532334761186 14R/32L 2024-12-02
40.49249810687566 -3.5765803943980825 18R/36L 2024-12-03
40.4924864688162 -3.5765179720791904 18R/36L 2024-12-05
40.49942779541016 -3.56121826171875 18L/36R 2024-12-02
40.49943923950195 -3.5612335205078125 18L/36R 2024-12-03
40.49184637554621 -3.572616577148437 18R/36L 2024-12-04
40.491788185248936 -3.5763931274414062 18R/36L 2024-12-07
40.48393249511719 -3.577594757080078 14R/32L 2024-12-02
40.492469787597656 -3.57659912109375 18R/36L 2024-12-04
40.49174880981445 -3.576446533203125 18R/36L 2024-12-06
40.49176490913003 -3.576439944180575 18R/36L 2024-12-04
40.49184036254883 -3.5726318359375 18R/36L 2024-12-07
40.49942275225106 -3.5612401095303623 18L/36R 2024-12-04
40.49174880981445 -3.5764617919921875 18R/36L 2024-12-04
40.49942779541016 -3.5612335205078125 18L/36R 2024-12-04
40.49943439031051 -3.5612401095303623 18L/36R 2024-12-03
40.49943923950195 -3.56121826171875 18L/36R 2024-12-04
40.49943439031051 -3.5612401095303623 18L/36R 2024-12-07
40.49247483075675 -3.5766116055575283 18R/36L 2024-12-07
40.50036543506687 -3.561224503950639 18L/36R 2024-12-05
40.50032043457031 -3.5612030029296875 18L/36R 2024-12-05
40.49187469482422 -3.572662353515625 18R/36L 2024-12-01
40.499473571777344 -3.5611724853515625 18L/36R 2024-12-02
40.49942275225106 -3.561224503950639 18L/36R 2024-12-01
40.49942275225106 -3.561208898370916 18L/36R 2024-12-05
40.492469787597656 -3.5765380859375 18R/36L 2024-12-06
40.49941635131836 -3.56121826171875 18L/36R 2024-12-02
40.49943439031051 -3.5612401095303623 18L/36R 2024-12-05
40.49152050988149 -3.5762370716441763 18R/36L 2024-12-03
40.49187469482422 -3.572616577148437 18R/36L 2024-12-03
40.49432373046875 -3.5597686767578125 14L/32R 2024-12-02
40.49944602836997 -3.5612401095303623 18L/36R 2024-12-02
40.49944602836997 -3.561208898370916 18L/36R 2024-12-04
40.49182891845703 -3.572616577148437 18R/36L 2024-12-01
40.48585510253906 -3.574462890625 14R/32L 2024-12-02
40.49153137207031 -3.576263427734375 18R/36L 2024-12-03
40.49942275225106 -3.561224503950639 18L/36R 2024-12-07
40.49152050988149 -3.5762370716441763 18R/36L 2024-12-07
40.49943923950195 -3.5612030029296875 18L/36R 2024-12-03
40.49943923950195 -3.5612335205078125 18L/36R 2024-12-06
40.49257957329184 -3.5766116055575283 18R/36L 2024-12-06
40.49154281616211 -3.5762481689453125 18R/36L 2024-12-04
40.48531742419227 -3.5753163424405185 18R/36L 2024-12-03
40.49248123168945 -3.576522827148437 18R/36L 2024-12-05
40.49944602836997 -3.5612401095303623 18L/36R 2024-12-06
40.49184036254883 -3.57275390625 18R/36L 2024-12-07
40.4924864688162 -3.5766116055575283 18R/36L 2024-12-06
40.49942275225106 -3.5612401095303623 18L/36R 2024-12-06
40.49942275225106 -3.561224503950639 18L/36R 2024-12-02
40.49155426025391 -3.5762176513671875 18R/36L 2024-12-05
40.49061274124404 -3.5725385492498223 18R/36L 2024-12-04
40.49946212768555 -3.56121826171875 18L/36R 2024-12-05
40.49941635131836 -3.56121826171875 18L/36R 2024-12-04
40.492469787597656 -3.5764617919921875 18R/36L 2024-12-03
40.49941635131836 -3.56121826171875 18L/36R 2024-12-04
40.4838981628418 -3.5775299072265625 14R/32L 2024-12-02
40.491532147940944 -3.576252677223899 18R/36L 2024-12-06
40.49177169799805 -3.5764617919921875 18R/36L 2024-12-03
40.49150887182204 -3.576252677223899 18R/36L 2024-12-01
40.49151992797852 -3.5762481689453125 18R/36L 2024-12-06
40.49072912183858 -3.5725541548295454 18R/36L 2024-12-07
40.49943439031051 -3.561224503950639 18L/36R 2024-12-05
40.49942779541016 -3.561187744140625 18L/36R 2024-12-05
40.49944602836997 -3.561224503950639 18L/36R 2024-12-04
40.49942779541016 -3.5612335205078125 18L/36R 2024-12-03
40.49249267578125 -3.5766143798828125 18R/36L 2024-12-04
40.499473571777344 -3.56121826171875 18L/36R 2024-12-07
40.49150887182204 -3.576221466064453 18R/36L 2024-12-05
40.49182891845703 -3.5726318359375 18R/36L 2024-12-07
40.49247483075675 -3.5765803943980825 18R/36L 2024-12-03
40.49184637554621 -3.5726633938876065 18R/36L 2024-12-03
40.49247483075675 -3.5766116055575283 18R/36L 2024-12-02
40.49941635131836 -3.5612335205078125 18L/36R 2024-12-06
40.50029754638672 -3.5612030029296875 18L/36R 2024-12-04
40.49249267578125 -3.5765533447265625 18R/36L 2024-12-03
40.49176490913003 -3.5764555497602983 18R/36L 2024-12-04
40.49942779541016 -3.56121826171875 18L/36R 2024-12-02
40.49433517456055 -3.559799194335937 14L/32R 2024-12-02
40.49945068359375 -3.5612335205078125 18L/36R 2024-12-04
40.49052429199219 -3.57293701171875 18R/36L 2024-12-04
40.49941635131836 -3.56121826171875 18L/36R 2024-12-03
40.49942779541016 -3.561187744140625 18L/36R 2024-12-06
40.49249810687566 -3.5766116055575283 18R/36L 2024-12-06
40.49944602836997 -3.5612401095303623 18L/36R 2024-12-05
40.49150887182204 -3.576252677223899 18R/36L 2024-12-02
40.49176490913003 -3.5764087330211294 18R/36L 2024-12-07
40.49942275225106 -3.5612401095303623 18L/36R 2024-12-01
40.50029560671014 -3.561208898370916 18L/36R 2024-12-06
40.49942275225106 -3.561208898370916 18L/36R 2024-12-05
40.4994111141916 -3.561193292791193 18L/36R 2024-12-03
40.49184036254883 -3.572616577148437 18R/36L 2024-12-03
40.50029754638672 -3.56121826171875 18L/36R 2024-12-01
40.49186325073242 -3.572616577148437 18R/36L 2024-12-04
40.49942779541016 -3.56121826171875 18L/36R 2024-12-01
40.49941635131836 -3.5612335205078125 18L/36R 2024-12-04
40.49176025390625 -3.5764617919921875 18R/36L 2024-12-05
40.49184637554621 -3.5726321827281606 18R/36L 2024-12-05
40.49942779541016 -3.5612030029296875 18L/36R 2024-12-06
40.49943439031051 -3.561208898370916 18L/36R 2024-12-01
40.49056618900622 -3.5725385492498223 18R/36L 2024-12-01
40.49942779541016 -3.5612335205078125 18L/36R 2024-12-03
40.49942275225106 -3.56117768721147 18L/36R 2024-12-02
40.49247483075675 -3.5766116055575283 18R/36L 2024-12-03
40.49942275225106 -3.561208898370916 18L/36R 2024-12-02
40.49942779541016 -3.5612030029296875 18L/36R 2024-12-04
40.49939947613215 -3.5612401095303623 18L/36R 2024-12-01
40.49152050988149 -3.576252677223899 18R/36L 2024-12-03
40.49942275225106 -3.561224503950639 18L/36R 2024-12-07
40.49942779541016 -3.5612335205078125 18L/36R 2024-12-06
40.49151992797852 -3.5762481689453125 18R/36L 2024-12-02
40.49153137207031 -3.576263427734375 18R/36L 2024-12-03
40.49249267578125 -3.576522827148437 18R/36L 2024-12-06
40.49247483075675 -3.5765803943980825 18R/36L 2024-12-05
40.49250411987305 -3.576568603515625 18R/36L 2024-12-05
40.49945068359375 -3.5612030029296875 18L/36R 2024-12-07
40.49247483075675 -3.5765803943980825 18R/36L 2024-12-01
40.49945068359375 -3.5612030029296875 18L/36R 2024-12-07
40.49154378600039 -3.576252677223899 18R/36L 2024-12-05
40.49945766642942 -3.5612401095303623 18L/36R 2024-12-04
40.49189292778403 -3.576486760919744 18R/36L 2024-12-05
40.49942275225106 -3.561208898370916 18L/36R 2024-12-04
40.49150887182204 -3.5762370716441763 18R/36L 2024-12-07
40.49942779541016 -3.561141967773437 18L/36R 2024-12-01
40.49250411987305 -3.5764923095703125 18R/36L 2024-12-07
40.49942275225106 -3.5612401095303623 18L/36R 2024-12-01
40.49945766642942 -3.561224503950639 18L/36R 2024-12-05
40.48586441298662 -3.5744892467151987 14R/32L 2024-12-02
40.49248123168945 -3.5765838623046875 18R/36L 2024-12-01
40.49151992797852 -3.5762481689453125 18R/36L 2024-12-06
40.49944602836997 -3.5612401095303623 18L/36R 2024-12-01
40.49942275225106 -3.561208898370916 18L/36R 2024-12-04
40.49174880981445 -3.576400756835937 18R/36L 2024-12-07
40.49943439031051 -3.5612401095303623 18L/36R 2024-12-03
40.49945766642942 -3.561224503950639 18L/36R 2024-12-02
40.49251556396485 -3.5765380859375 18R/36L 2024-12-04
40.49250974493511 -3.57656478881836 18R/36L 2024-12-05
40.49248123168945 -3.5766143798828125 18R/36L 2024-12-05
40.48582077026367 -3.5745086669921875 14R/32L 2024-12-02
40.49249810687566 -3.576424338600852 18R/36L 2024-12-02
40.4916718046544 -3.5764087330211294 14R/32L 2024-12-02
40.49942275225106 -3.561208898370916 18L/36R 2024-12-05
40.49942275225106 -3.561208898370916 18L/36R 2024-12-04
40.49245834350586 -3.576568603515625 18R/36L 2024-12-05
40.49939947613215 -3.5612401095303623 18L/36R 2024-12-04
40.49942275225106 -3.5612401095303623 18L/36R 2024-12-06
40.5003776550293 -3.56121826171875 18L/36R 2024-12-04
40.4994111141916 -3.561224503950639 18L/36R 2024-12-02
40.49943439031051 -3.5612401095303623 18L/36R 2024-12-06
40.49943439031051 -3.561208898370916 18L/36R 2024-12-03
40.49247483075675 -3.576595999977805 18R/36L 2024-12-05
40.49177654718948 -3.576471155340021 18R/36L 2024-12-01
40.49189292778403 -3.5763931274414062 18R/36L 2024-12-04
40.49248123168945 -3.576507568359375 18R/36L 2024-12-05
40.49150887182204 -3.576252677223899 18R/36L 2024-12-06
40.49036407470703 -3.57269287109375 18R/36L 2024-12-05
40.49950421866724 -3.561224503950639 18L/36R 2024-12-07
40.49942779541016 -3.56121826171875 18L/36R 2024-12-02
40.49253845214844 -3.5765533447265625 18R/36L 2024-12-03
40.49942275225106 -3.561224503950639 18L/36R 2024-12-02
40.49190456584349 -3.5727102106267754 18R/36L 2024-12-05
40.49039161811441 -3.5727726329456675 18R/36L 2024-12-05
40.49942275225106 -3.5612401095303623 18L/36R 2024-12-02
40.49942779541016 -3.5612335205078125 18L/36R 2024-12-01
40.49152050988149 -3.576252677223899 18R/36L 2024-12-04
40.491881289724574 -3.572647788307884 18R/36L 2024-12-02
40.49249810687566 -3.57656478881836 18R/36L 2024-12-06
40.49931800971597 -3.561208898370916 18L/36R 2024-12-02
40.49944602836997 -3.561208898370916 18L/36R 2024-12-02
40.49067093154131 -3.5725073380903765 18R/36L 2024-12-05
40.49951934814453 -3.5612335205078125 18L/36R 2024-12-06
40.49942779541016 -3.5612335205078125 18L/36R 2024-12-04
40.49411579713983 -3.558415499600497 18L/36R 2024-12-02
40.49941635131836 -3.5612335205078125 18L/36R 2024-12-04
40.49184637554621 -3.5726946050470523 18R/36L 2024-12-02
40.4994111141916 -3.56117768721147 18L/36R 2024-12-06
40.49942275225106 -3.561224503950639 18L/36R 2024-12-05
40.49149723376258 -3.5762370716441763 18R/36L 2024-12-02
40.49942275225106 -3.561224503950639 18L/36R 2024-12-06
40.50040054321289 -3.5612030029296875 18L/36R 2024-12-06
40.49942275225106 -3.561208898370916 18L/36R 2024-12-06
40.49942275225106 -3.561208898370916 18L/36R 2024-12-07
40.49190456584349 -3.5726633938876065 18R/36L 2024-12-05
40.49951934814453 -3.5612335205078125 18L/36R 2024-12-03
40.49953079223633 -3.5612030029296875 18L/36R 2024-12-07
40.491532147940944 -3.576268282803622 18R/36L 2024-12-04
40.49150848388672 -3.5762176513671875 18R/36L 2024-12-07
40.490501403808594 -3.5726776123046875 18R/36L 2024-12-05
40.49248123168945 -3.5764617919921875 18R/36L 2024-12-05
40.49945068359375 -3.5611114501953125 18L/36R 2024-12-03
40.49184036254883 -3.576400756835937 18R/36L 2024-12-05
40.49249267578125 -3.576568603515625 18R/36L 2024-12-01
40.49943923950195 -3.5612030029296875 18L/36R 2024-12-04
40.49944602836997 -3.561224503950639 18L/36R 2024-12-05
40.49942275225106 -3.5612401095303623 18L/36R 2024-12-04
40.49942275225106 -3.561193292791193 18L/36R 2024-12-03
40.49944602836997 -3.561224503950639 18L/36R 2024-12-02
40.49943923950195 -3.56121826171875 18L/36R 2024-12-05
40.48482862569518 -3.578109741210937 14R/32L 2024-12-02
40.49190902709961 -3.572616577148437 18R/36L 2024-12-05
40.49248123168945 -3.5766143798828125 18R/36L 2024-12-05
40.49942779541016 -3.5611724853515625 18L/36R 2024-12-05
40.491881289724574 -3.5727102106267754 18R/36L 2024-12-01
40.49189758300781 -3.5764617919921875 18R/36L 2024-12-05
40.49943439031051 -3.561224503950639 18L/36R 2024-12-01
40.49248123168945 -3.576568603515625 18R/36L 2024-12-05
40.49942275225106 -3.5612401095303623 18L/36R 2024-12-01
40.47241081625728 -3.537862951105291 18R/36L 2024-12-02
40.49943439031051 -3.56117768721147 18L/36R 2024-12-04
40.4924864688162 -3.5766116055575283 18R/36L 2024-12-06
40.4915670621193 -3.5762370716441763 18R/36L 2024-12-04
40.49163436889648 -3.576202392578125 18R/36L 2024-12-07
40.49943439031051 -3.561208898370916 18L/36R 2024-12-06
40.49941635131836 -3.5612335205078125 18L/36R 2024-12-07
40.49150887182204 -3.5762370716441763 18R/36L 2024-12-05
40.49941635131836 -3.5612335205078125 18L/36R 2024-12-03
40.49943923950195 -3.5612030029296875 18L/36R 2024-12-06
40.49942275225106 -3.561224503950639 18L/36R 2024-12-07
40.49171447753906 -3.576171875 18R/36L 2024-12-06
40.49150848388672 -3.5762176513671875 18R/36L 2024-12-02
40.49946930448888 -3.561224503950639 18L/36R 2024-12-07
40.49155542405985 -3.5762370716441763 18R/36L 2024-12-04
40.4919278419624 -3.5726633938876065 18R/36L 2024-12-07
40.49247483075675 -3.57656478881836 18R/36L 2024-12-01
40.49945068359375 -3.5612335205078125 18L/36R 2024-12-03
40.49247483075675 -3.5766116055575283 18R/36L 2024-12-03
40.49186325073242 -3.5726470947265625 18R/36L 2024-12-03
40.491532147940944 -3.576268282803622 18R/36L 2024-12-03
40.49184036254883 -3.5726470947265625 18R/36L 2024-12-03
40.49067306518555 -3.572540283203125 18R/36L 2024-12-03
40.49943439031051 -3.561208898370916 18L/36R 2024-12-06
40.491881289724574 -3.572616577148437 18R/36L 2024-12-03
40.49251556396485 -3.57659912109375 18R/36L 2024-12-07
40.49943439031051 -3.5612401095303623 18L/36R 2024-12-01
40.49248123168945 -3.5766143798828125 18R/36L 2024-12-06
40.50041198730469 -3.561193292791193 18L/36R 2024-12-06
40.49037998005495 -3.5726946050470523 18R/36L 2024-12-03
40.49153137207031 -3.5762481689453125 18R/36L 2024-12-07
40.49944602836997 -3.561193292791193 18L/36R 2024-12-02
40.49152050988149 -3.576252677223899 18R/36L 2024-12-03
40.49154378600039 -3.576268282803622 18R/36L 2024-12-06
40.49248123168945 -3.576568603515625 18R/36L 2024-12-01
40.49943439031051 -3.561208898370916 18L/36R 2024-12-01
40.49155426025391 -3.57623291015625 18R/36L 2024-12-07
40.48584113686771 -3.5744892467151987 14R/32L 2024-12-02
40.49943923950195 -3.56121826171875 18L/36R 2024-12-05
40.49942275225106 -3.561224503950639 18L/36R 2024-12-03
40.49944602836997 -3.561208898370916 18L/36R 2024-12-07
40.491811461367845 -3.576486760919744 18R/36L 2024-12-01
40.49186325073242 -3.572616577148437 18R/36L 2024-12-01
40.49942275225106 -3.561208898370916 18L/36R 2024-12-06
40.49184036254883 -3.572616577148437 18R/36L 2024-12-03
40.49247483075675 -3.5766116055575283 18R/36L 2024-12-07
40.49941635131836 -3.5612335205078125 18L/36R 2024-12-05
40.4924864688162 -3.5765803943980825 18R/36L 2024-12-03
40.4994111141916 -3.5612401095303623 18L/36R 2024-12-05
40.50029754638672 -3.5612030029296875 18L/36R 2024-12-04
40.49057782706568 -3.5725385492498223 18R/36L 2024-12-04
40.49249267578125 -3.57659912109375 18R/36L 2024-12-07
40.492469787597656 -3.57659912109375 18R/36L 2024-12-06
40.49941635131836 -3.5612335205078125 18L/36R 2024-12-02
40.50029754638672 -3.5612335205078125 18L/36R 2024-12-03
40.48586441298662 -3.574458035555753 14R/32L 2024-12-02
40.49946930448888 -3.5612401095303623 18L/36R 2024-12-02
40.49248123168945 -3.5765533447265625 18R/36L 2024-12-03
40.49943439031051 -3.561224503950639 18L/36R 2024-12-05
40.49152050988149 -3.576252677223899 18R/36L 2024-12-07
40.49186325073242 -3.572616577148437 18R/36L 2024-12-07
40.49248123168945 -3.57659912109375 18R/36L 2024-12-06
40.49175327107058 -3.5764555497602983 18R/36L 2024-12-05
40.49942275225106 -3.5612401095303623 18L/36R 2024-12-03
40.48681640625 -3.5747222900390625 14R/32L 2024-12-02
40.49248123168945 -3.5765838623046875 18R/36L 2024-12-06
40.49149723376258 -3.5762370716441763 18R/36L 2024-12-04
40.49247483075675 -3.57656478881836 18R/36L 2024-12-05
40.49946212768555 -3.5612030029296875 18L/36R 2024-12-04
40.48649286819717 -3.57522270896218 14R/32L 2024-12-02
40.49151992797852 -3.576263427734375 18R/36L 2024-12-04

In [15]:
df[(df["llegada_lon"] == -3.5371246337890625) & (df["llegada_lat"] == 40.46636581420898)]

,ICAO,llegada_punto,salida_punto,despegue,tiempo_espera,aircraft_type,llegada_lon,llegada_lat,salida_lon,salida_lat,holding_point,parado,runway,fecha_despegue,hora_despegue
1011,347288,2024-12-04 06:08:25.625,2024-12-04 06:11:58.666,2024-12-04 07:44:23.053,5757.428,Medium 2 (between 34000 kg to 136000 kg),-3.537125,40.466366,-3.536789,40.471355,KA8,False,18L/36R,2024-12-04,7

In [16]:
sec = set()
df_sec = df.sort_values(by=["ICAO", "despegue"])
actual = None
despegue_actual = None
lista_prov=[]
for _, fila in df_sec.iterrows():
    if ((actual == None) | (fila["ICAO"]!=actual)):
        actual = fila["ICAO"]
        despegue_actual = fila["despegue"]
        if len(lista_prov)>0:
            sec.add(tuple(lista_prov))
            lista_prov = []
    if fila["despegue"] == despegue_actual:
        holding_point=fila["holding_point"]
        if len(lista_prov)>0:
            if lista_prov[-1] != holding_point:
                lista_prov.append(holding_point)
        else:
            lista_prov.append(holding_point)
    if fila["despegue"] != despegue_actual:
        sec.add(tuple(lista_prov))
        lista_prov = []
print(sec)

{('Z1', 'Z3'), ('LC',), ('KA6', 'Y1'), ('KA6', 'KA8', 'Z3'), ('Z4', 'Z6', 'Z2'), ('L1', 'Z2'), ('LA', 'L1', 'Y1'), ('Z3',), ('KA8', 'KA6', 'Z3'), ('K3', 'Z3'), ('L1', 'Y1'), ('Y3',), ('Z4',), ('K3', 'Z4'), ('LA',), ('K2',), ('Y2',), ('KA8', 'LE'), ('KA6', 'KA8', 'LE'), ('Z2',), ('Y1',), ('K1',), ('Z2', 'LC'), ('LE',), ('LE', 'Z1'), ('K3', 'Y1'), ('Z1',), ()}

In [17]:
import pandas as pd
a = df_sec.groupby(["ICAO","despegue"])["holding_point"].unique()
pd.set_option("display.max_rows", 500)
a.value_counts()

holding_point
[Y1]              1615
[Z2]               782
[Z4]               680
[Z3]               349
[Y2]               146
[Z1]               122
[K2]                54
[Y3]                31
[LE]                23
[LA]                14
[LC]                13
[K1]                 8
[LB]                 4
[KA6, KA8, Z3]       1
[L1, Y1]             1
[KA6, Z3]            1
[K3, Z2]             1
[L1, Y1]             1
[KA6, KA8, Z4]       1
[Z1, Z3]             1
[Z1, Z3]             1
[Z1, Z3]             1
[Z1, Z3]             1
[L1, Y1]             1
[Z2, LC]             1
[Y1, Y3, Y2]         1
[L1, Y1]             1
[LA, L1, Z2]         1
[L1, Z2]             1
[L1, Y1]             1
[L1, Y1]             1
[L1, Z2]             1
[L1, Y1]             1
[Z2, LC]             1
[LA, L1, Y1]         1
[LA, L1, Y1]         1
[L1, Y1]             1
[LA, Y1]             1
[L1, Z2]             1
[K3, Y1]             1
[Z6, Z2]             1
[Z4, Z6, Z2]         1
[KA6, KA8, Z3]       1
[K3, Z4]             1
[KA8, KA6, Z3]       1
[LD, LC]             1
[LE, Z3]             1
[L1, Y1]             1
[Z4, Z6]             1
[LD, LC]             1
[KA6, KA8, Z3]       1
[KA6, KA8, LE]       1
[LD, LC]             1
[LA, L1, Y1]         1
[LD, LC]             1
[LF, Z4]             1
[LD, LC]             1
[LD, LC]             1
[KA6, KA8, Y1]       1
[KA6, KA8, Y1]       1
[LD, LC]             1
[K3, Y3]             1
[K3, Z2]             1
[LE, Z1]             1
[L1, Y1]             1
[LA, Z2]             1
[LD, LC]             1
[KA8, LE]            1
[KA6, Y2]            1
[Z1, Z3]             1
[Z1, Z3]             1
[KA6, KA8, Z3]       1
[K3, Z3]             1
[KA6, KA8, Z1]       1
[K1, Z3]             1
[K3, Z3]             1
[KA8, KA6, Y1]       1
[KA6, Y1]            1
[KA6, KA8, LE]       1
[KA6, KA8, Z4]       1
[LE, Z1]             1
Name: count, dtype: int64