In [157]:
#import dask.dataframe as dd
import pandas as pd
from sklearn.preprocessing import StandardScaler,OneHotEncoder
df = pd.read_csv("/Users/hamzatriki/3ºProyectoDeDatos2/PD2/data/ex1/eventos_espera_semana_antiguo.txt", delimiter=",")
df

,ICAO,ultimo_parado,despegue,tiempo_espera,aircraft_type,lat,lon,fecha_despegue,hora_despegue,runway
0,3C5434,2024-12-03 08:17:54.070,2024-12-03 08:28:40.767,646.697,High vortex aircraft,40.496109,-3.574646,2024-12-03,8,18R/36L
1,3C5434,2024-12-03 21:14:30.880,2024-12-03 21:14:49.599,18.719,High vortex aircraft,40.504939,-3.559227,2024-12-03,21,18L/36R
2,44046D,2024-12-01 19:13:45.545,2024-12-01 19:31:45.660,1080.115,High vortex aircraft,40.505637,-3.559243,2024-12-01,19,18L/36R
3,4952CE,2024-12-01 06:55:32.575,2024-12-01 06:55:53.525,20.950,High vortex aircraft,40.496990,-3.574631,2024-12-01,6,18R/36L
4,E8043B,2024-12-02 23:45:55.121,2024-12-02 23:46:35.072,39.951,High vortex aircraft,40.497803,-3.574615,2024-12-02,23,18R/36L
...,...,...,...,...,...,...,...,...,...,...
4033,4D24C4,2024-12-01 20:13:19.998,2024-12-07 17:47:15.489,509635.491,High vortex aircraft,40.469490,-3.566833,2024-12-07,17,14R/32L
4034,4D24C4,2024-12-07 20:13:29.428,2024-12-07 20:15:19.335,109.907,High vortex aircraft,40.505428,-3.559227,2024-12-07,20,18L/36R
4035,A07176,2024-12-02 10:08:36.593,2024-12-02 10:10:56.205,139.612,High vortex aircraft,40.481152,-3.572220,2024-12-02,10,14R/32L
4036,A07176,2024-12-05 23:06:11.578,2024-12-05 23:06:50.548,38.970,High vortex aircraft,40.497828,-3.574630,2024-12-05,23,18R/36L
4037,A1CC30,2024-12-07 10:34:15.539,2024-12-07 11:55:31.557,4876.018,High vortex aircraft,40.505149,-3.559227,2024-12-07,11,18L/36R

In [160]:
df.dtypes

ICAO               object
ultimo_parado      object
despegue           object
tiempo_espera     float64
aircraft_type      object
lat               float64
lon               float64
fecha_despegue     object
hora_despegue       int64
runway             object
dtype: object

In [161]:
df[df["ICAO"] == "344307"]

,ICAO,ultimo_parado,despegue,tiempo_espera,aircraft_type,lat,lon,fecha_despegue,hora_despegue,runway
2931,344307,2024-12-01 06:59:52.548,2024-12-01 07:00:19.044,26.496,High vortex aircraft,40.498066,-3.574631,2024-12-01,7,18R/36L
2932,344307,2024-12-01 12:34:51.600,2024-12-01 12:35:15.165,23.565,High vortex aircraft,40.498736,-3.574630,2024-12-01,12,18R/36L
2933,344307,2024-12-01 17:27:48.631,2024-12-01 17:34:19.956,391.325,High vortex aircraft,40.498864,-3.574630,2024-12-01,17,18R/36L
2934,344307,2024-12-02 07:09:50.060,2024-12-02 07:12:17.605,147.545,Heavy (larger than 136000 kg),40.498569,-3.574646,2024-12-02,7,18R/36L
2935,344307,2024-12-03 08:28:48.736,2024-12-03 08:31:13.402,144.666,High vortex aircraft,40.497991,-3.574677,2024-12-03,8,18R/36L
2936,344307,2024-12-03 16:54:20.875,2024-12-03 17:00:12.957,352.082,High vortex aircraft,40.497665,-3.574645,2024-12-03,17,18R/36L
2937,344307,2024-12-04 06:58:30.149,2024-12-04 06:58:59.202,29.053,High vortex aircraft,40.497494,-3.574631,2024-12-04,6,18R/36L
2938,344307,2024-12-05 06:51:37.667,2024-12-05 06:52:58.384,80.717,High vortex aircraft,40.498864,-3.574661,2024-12-05,6,18R/36L
2939,344307,2024-12-06 07:27:20.109,2024-12-06 07:33:35.635,375.526,High vortex aircraft,40.497037,-3.574630,2024-12-06,7,18R/36L
2940,344307,2024-12-06 14:04:14.291,2024-12-06 14:04:44.784,30.493,Heavy (larger than 136000 kg),40.505447,-3.559235,2024-12-06,14,18L/36R
2941,344307,2024-12-07 06:59:45.939,2024-12-07 07:00:29.061,43.122,Rotorcraft,40.497479,-3.574630,2024-12-07,7,18R/36L

In [91]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1296 entries, 0 to 1295
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ICAO            1296 non-null   object
 1   ultimo_parado   1296 non-null   object
 2   despegue        1296 non-null   object
 3   tiempo_espera   1296 non-null   float64
 4   aircraft_type   1296 non-null   object
 5   lat             1296 non-null   float64
 6   lon             1296 non-null   float64
 7   holding_point   1296 non-null   object
 8   fecha_despegue  1296 non-null   object
 9   hora_despegue   1296 non-null   int64
 10  runway          1295 non-null   object
dtypes: float64(3), int64(1), object(7)
memory usage: 111.5+ KB

In [92]:
icaos = df[["ICAO","tiempo_espera"]]
#df = df.drop(columns = "ICAO")
df.head()

,ICAO,ultimo_parado,despegue,tiempo_espera,aircraft_type,lat,lon,holding_point,fecha_despegue,hora_despegue,runway
0,3420ca,2024-12-03 15:21:22.843,2024-12-03 15:23:03.503,100.660,Medium 2 (between 34000 kg to 136000 kg),40.505962,-3.559235,Y2,2024-12-03,15,18L/36R
1,3420ca,2024-12-04 09:24:55.891,2024-12-04 09:26:36.177,100.286,Medium 2 (between 34000 kg to 136000 kg),40.504462,-3.559211,Y1,2024-12-04,9,18L/36R
2,3420ca,2024-12-04 16:16:10.860,2024-12-04 16:17:46.200,95.340,Medium 2 (between 34000 kg to 136000 kg),40.498638,-3.574646,Z4,2024-12-04,16,18R/36L
3,3420ca,2024-12-07 20:14:55.509,2024-12-07 20:16:48.101,112.592,Medium 2 (between 34000 kg to 136000 kg),40.504613,-3.559211,Y1,2024-12-07,20,18L/36R
4,3444c3,2024-12-02 14:42:10.407,2024-12-02 14:43:51.726,101.319,Medium 2 (between 34000 kg to 136000 kg),40.505824,-3.559227,Y1,2024-12-02,14,18L/36R

In [93]:
icaos

        ICAO  tiempo_espera
0     3420ca        100.660
1     3420ca        100.286
2     3420ca         95.340
3     3420ca        112.592
4     3444c3        101.319
...      ...            ...
1291  345597        147.842
1292  345597         34.262
1293  345597        121.966
1294  4d22b1        119.133
1295  738051        103.408

[1296 rows x 2 columns]

In [94]:
df.dtypes

ICAO               object
ultimo_parado      object
despegue           object
tiempo_espera     float64
aircraft_type      object
lat               float64
lon               float64
holding_point      object
fecha_despegue     object
hora_despegue       int64
runway             object
dtype: object

In [95]:
## Cargar bien los tiempos
timestap_columns = ["ultimo_parado","despegue"]
for col in timestap_columns:
    df[col] = pd.to_datetime(df[col],format="%Y-%m-%d %H:%M:%S.%f")
df["fecha_despegue"] = pd.to_datetime(df["fecha_despegue"],format="%Y-%m-%d")
df.dtypes

ICAO                      object
ultimo_parado     datetime64[ns]
despegue          datetime64[ns]
tiempo_espera            float64
aircraft_type             object
lat                      float64
lon                      float64
holding_point             object
fecha_despegue    datetime64[ns]
hora_despegue              int64
runway                    object
dtype: object

In [96]:
categorical_columns = df.select_dtypes("object")
categorical_columns.columns.drop("ICAO")

Index(['aircraft_type', 'holding_point', 'runway'], dtype='object')

In [97]:
encoder = OneHotEncoder(sparse_output=False)

categorical_columns = df.select_dtypes("object").columns.drop("ICAO")

encoded_data = encoder.fit_transform(df[categorical_columns])

df_encoded = pd.DataFrame(encoded_data, columns = encoder.get_feature_names_out())
df = df.drop(columns = categorical_columns)
df_encoded = pd.concat([df,df_encoded],axis = 1)

In [98]:
df_encoded.sort_values("ultimo_parado")

,ICAO,ultimo_parado,despegue,tiempo_espera,lat,lon,fecha_despegue,hora_despegue,aircraft_type_Heavy (larger than 136000 kg),aircraft_type_High vortex aircraft,...,holding_point_Z1,holding_point_Z2,holding_point_Z3,holding_point_Z4,holding_point_Z6,runway_14L/32R,runway_14R/32L,runway_18L/36R,runway_18R/36L,runway_nan
217,aac33e,2024-12-01 00:38:08.329,2024-12-01 00:39:48.750,100.421,40.497735,-3.574645,2024-12-01,0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
533,4cada6,2024-12-01 04:59:49.165,2024-12-01 05:00:56.920,67.755,40.498247,-3.574645,2024-12-01,5,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
15,4ca75f,2024-12-01 05:00:43.211,2024-12-01 05:02:49.620,126.409,40.498538,-3.574645,2024-12-01,5,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
911,4ca225,2024-12-01 05:24:47.645,2024-12-01 05:26:49.631,121.986,40.498123,-3.574646,2024-12-01,5,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
64,4ca2c0,2024-12-01 05:26:45.264,2024-12-01 05:28:43.020,117.756,40.497826,-3.574646,2024-12-01,5,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
280,8964c3,2024-12-07 20:28:29.504,2024-12-07 20:29:46.648,77.144,40.504509,-3.559211,2024-12-07,20,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
527,06a2f2,2024-12-07 21:10:20.045,2024-12-07 21:11:43.880,83.835,40.507081,-3.559227,2024-12-07,21,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
9,346188,2024-12-07 22:02:14.048,2024-12-07 22:04:48.160,154.112,40.496521,-3.574814,2024-12-07,22,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
371,345686,2024-12-07 22:08:30.532,2024-12-07 22:10:10.102,99.570,40.497118,-3.574817,2024-12-07,22,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
672,4cad3d,2024-12-07 23:14:53.199,2024-12-07 23:17:51.093,177.894,40.497153,-3.574630,2024-12-07,23,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [99]:
## df_encoded.reset_index()

In [100]:
df_encoded["tiempo_espera_nuevo"] = (df_encoded["despegue"] - df_encoded["ultimo_parado"]).dt.total_seconds()
df_encoded["tiempo_espera_nuevo"]

0       100.660
1       100.286
2        95.340
3       112.592
4       101.319
         ...
1291    147.842
1292     34.262
1293    121.966
1294    119.133
1295    103.408
Name: tiempo_espera_nuevo, Length: 1296, dtype: float64

In [101]:
df_encoded["ICAO"]

0       3420ca
1       3420ca
2       3420ca
3       3420ca
4       3444c3
         ...
1291    345597
1292    345597
1293    345597
1294    4d22b1
1295    738051
Name: ICAO, Length: 1296, dtype: object

In [102]:
for avion, datos in df_encoded.groupby("ICAO"):  # 🔹 Agrupamos los datos por cada avión
    datos = datos.sort_values("ultimo_parado")

In [111]:
df_encoded.loc[0,"ultimo_parado"]

Timestamp('2024-12-03 15:21:22.843000')

In [107]:
tiempo_referencia 
for fila in df_encoded.iterrows()
    tiempo_referencia = fila["ultimo_parado"]
    for subfila in df_encoded.iterrows():
        if fila != subfila:
            df_encoded.apply(lambda row: calcular_tiempo_relativo(tiempo_referencia,row["despegue"])

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

(1089, ICAO                                                                          344417
ultimo_parado                                             2024-12-03 15:08:38.077000
despegue                                                  2024-12-03 15:10:03.283000
tiempo_espera                                                                 85.206
lat                                                                        40.498643
lon                                                                        -3.574661
fecha_despegue                                                   2024-12-03 00:00:00
hora_despegue                                                                     15
aircraft_type_Heavy (larger than 136000 kg)                                      0.0
aircraft_type_High vortex aircraft                                               0.0
aircraft_type_Light (less than 7000 kg)                                          0.0
aircraft_type_Medium 1 (between 7000 kg and 34000 kg)                            0.0
aircraft_type_Medium 2 (between 34000 kg to 136000 kg)                           1.0
aircraft_type_No category information                                            0.0
holding_point_K1                                                                 0.0
holding_point_K2                                                                 0.0
holding_point_KA6                                                                0.0
holding_point_KA8                                                                0.0
holding_point_LA                                                                 0.0
holding_point_LB                                                                 0.0
holding_point_LC                                                                 0.0
holding_point_LD                                                                 0.0
holding_point_LE                                                                 0.0
holding_point_Y1                                                                 0.0
holding_point_Y2                                                                 0.0
holding_point_Y3                                                                 0.0
holding_point_Z1                                                                 0.0
holding_point_Z2                                                                 0.0
holding_point_Z3                                                                 0.0
holding_point_Z4                                                                 1.0
holding_point_Z6                                                                 0.0
runway_14L/32R                                                                   0.0
runway_14R/32L                                                                   0.0
runway_18L/36R                                                                   0.0
runway_18R/36L                                                                   1.0
runway_nan                                                                       0.0
tiempo_espera_nuevo                                                           85.206
Name: 1089, dtype: object)
(1090, ICAO                                                                          344417
ultimo_parado                                             2024-12-05 08:25:37.235000
despegue                                                  2024-12-05 08:27:14.604000
tiempo_espera                                                                 97.369
lat                                                                        40.505093
lon                                                                        -3.559204
fecha_despegue                                                   2024-12-05 00:00:00
hora_despegue                                                                      8
aircraft_type_Heavy (larger than 136000 kg)                                      0.0
aircraft_type_High vortex aircraft                                               0.0
aircraft_type_Light (less than 7000 kg)                                          0.0
aircraft_type_Medium 1 (between 7000 kg and 34000 kg)                            0.0
aircraft_type_Medium 2 (between 34000 kg to 136000 kg)                           1.0
aircraft_type_No category information                                            0.0
holding_point_K1                                                                 0.0
holding_point_K2                                                                 0.0
holding_point_KA6                                                                0.0
holding_point_KA8                                                                0.0
holding_point_LA                                                                 0.0
holding_point_LB                                                                 0.0
holding_point_LC                                                                 0.0
holding_point_LD                                                                 0.0
holding_point_LE                                                                 0.0
holding_point_Y1                                                                 1.0
holding_point_Y2                                                                 0.0
holding_point_Y3                                                                 0.0
holding_point_Z1                                                                 0.0
holding_point_Z2                                                                 0.0
holding_point_Z3                                                                 0.0
holding_point_Z4                                                                 0.0
holding_point_Z6                                                                 0.0
runway_14L/32R                                                                   0.0
runway_14R/32L                                                                   0.0
runway_18L/36R                                                                   1.0
runway_18R/36L                                                                   0.0
runway_nan                                                                       0.0
tiempo_espera_nuevo                                                           97.369
Name: 1090, dtype: object)
(1091, ICAO                                                                          344417
ultimo_parado                                             2024-12-06 06:50:54.412000
despegue                                                  2024-12-06 06:52:02.804000
tiempo_espera                                                                 68.392
lat                                                                        40.505081
lon                                                                        -3.559219
fecha_despegue                                                   2024-12-06 00:00:00
hora_despegue                                                                      6
aircraft_type_Heavy (larger than 136000 kg)                                      0.0
aircraft_type_High vortex aircraft                                               0.0
aircraft_type_Light (less than 7000 kg)                                          0.0
aircraft_type_Medium 1 (between 7000 kg and 34000 kg)                            0.0
aircraft_type_Medium 2 (between 34000 kg to 136000 kg)                           1.0
aircraft_type_No category information                                            0.0
holding_point_K1                                                                 0.0
holding_point_K2                                                                 0.0
holding_point_KA6                                                                0.0
holding_point_KA8                                                                0.0
holding_point_LA                                                                 0.0
holding_point_LB                                                                 0.0
holding_point_LC                                                                 0.0
holding_point_LD                                                                 0.0
holding_point_LE                                                                 0.0
holding_point_Y1                                                                 1.0
holding_point_Y2                                                                 0.0
holding_point_Y3                                                                 0.0
holding_point_Z1                                                                 0.0
holding_point_Z2                                                                 0.0
holding_point_Z3                                                                 0.0
holding_point_Z4                                                                 0.0
holding_point_Z6                                                                 0.0
runway_14L/32R                                                                   0.0
runway_14R/32L                                                                   0.0
runway_18L/36R                                                                   1.0
runway_18R/36L                                                                   0.0
runway_nan                                                                       0.0
tiempo_espera_nuevo                                                           68.392
Name: 1091, dtype: object)
(1092, ICAO                                                                          344417
ultimo_parado                                             2024-12-07 07:23:59.266000
despegue                                                  2024-12-07 07:25:18.842000
tiempo_espera                                                                 79.576
lat                                                                        40.497921
lon                                                                        -3.574614
fecha_despegue                                                   2024-12-07 00:00:00
hora_despegue                                                                      7
aircraft_type_Heavy (larger than 136000 kg)                                      0.0
aircraft_type_High vortex aircraft                                               0.0
aircraft_type_Light (less than 7000 kg)                                          0.0
aircraft_type_Medium 1 (between 7000 kg and 34000 kg)                            0.0
aircraft_type_Medium 2 (between 34000 kg to 136000 kg)                           1.0
aircraft_type_No category information                                            0.0
holding_point_K1                                                                 0.0
holding_point_K2                                                                 0.0
holding_point_KA6                                                                0.0
holding_point_KA8                                                                0.0
holding_point_LA                                                                 0.0
holding_point_LB                                                                 0.0
holding_point_LC                                                                 0.0
holding_point_LD                                                                 0.0
holding_point_LE                                                                 0.0
holding_point_Y1                                                                 0.0
holding_point_Y2                                                                 0.0
holding_point_Y3                                                                 0.0
holding_point_Z1                                                                 0.0
holding_point_Z2                                                                 0.0
holding_point_Z3                                                                 0.0
holding_point_Z4                                                                 1.0
holding_point_Z6                                                                 0.0
runway_14L/32R                                                                   0.0
runway_14R/32L                                                                   0.0
runway_18L/36R                                                                   0.0
runway_18R/36L                                                                   1.0
runway_nan                                                                       0.0
tiempo_espera_nuevo                                                           79.576
Name: 1092, dtype: object)
(1093, ICAO                                                                          3475c7
ultimo_parado                                             2024-12-02 23:28:47.159000
despegue                                                  2024-12-02 23:31:42.467000
tiempo_espera                                                                175.308
lat                                                                        40.496967
lon                                                                        -3.574646
fecha_despegue                                                   2024-12-02 00:00:00
hora_despegue                                                                     23
aircraft_type_Heavy (larger than 136000 kg)                                      1.0
aircraft_type_High vortex aircraft                                               0.0
aircraft_type_Light (less than 7000 kg)                                          0.0
aircraft_type_Medium 1 (between 7000 kg and 34000 kg)                            0.0
aircraft_type_Medium 2 (between 34000 kg to 136000 kg)                           0.0
aircraft_type_No category information                                            0.0
holding_point_K1                                                                 0.0
holding_point_K2                                                                 0.0
holding_point_KA6                                                                0.0
holding_point_KA8                                                                0.0
holding_point_LA                                                                 0.0
holding_point_LB                                                                 0.0
holding_point_LC                                                                 0.0
holding_point_LD                                                                 0.0
holding_point_LE                                                                 0.0
holding_point_Y1                                                                 0.0
holding_point_Y2                                                                 0.0
holding_point_Y3                                                                 0.0
holding_point_Z1                                                                 1.0
holding_point_Z2                                                                 0.0
holding_point_Z3                                                                 0.0
holding_point_Z4                                                                 0.0
holding_point_Z6                                                                 0.0
runway_14L/32R                                                                   0.0
runway_14R/32L                                                                   0.0
runway_18L/36R                                                                   0.0
runway_18R/36L                                                                   1.0
runway_nan                                                                       0.0
tiempo_espera_nuevo                                                          175.308
Name: 1093, dtype: object)
(1094, ICAO                                                                          3475c7
ultimo_parado                                             2024-12-05 23:33:35.337000
despegue                                                  2024-12-05 23:35:02.122000
tiempo_espera                                                                 86.785
lat                                                                        40.497887
lon                                                                        -3.574645
fecha_despegue                                                   2024-12-05 00:00:00
hora_despegue                                                                     23
aircraft_type_Heavy (larger than 136000 kg)                                      1.0
aircraft_type_High vortex aircraft                                               0.0
aircraft_type_Light (less than 7000 kg)                                          0.0
aircraft_type_Medium 1 (between 7000 kg and 34000 kg)                            0.0
aircraft_type_Medium 2 (between 34000 kg to 136000 kg)                           0.0
aircraft_type_No category information                                            0.0
holding_point_K1                                                                 0.0
holding_point_K2                                                                 0.0
holding_point_KA6                                                                0.0
holding_point_KA8                                                                0.0
holding_point_LA                                                                 0.0
holding_point_LB                                                                 0.0
holding_point_LC                                                                 0.0
holding_point_LD                                                                 0.0
holding_point_LE                                                                 0.0
holding_point_Y1                                                                 0.0
holding_point_Y2                                                                 0.0
holding_point_Y3                                                                 0.0
holding_point_Z1                                                                 0.0
holding_point_Z2                                                                 0.0
holding_point_Z3                                                                 1.0
holding_point_Z4                                                                 0.0
holding_point_Z6                                                                 0.0
runway_14L/32R                                                                   0.0
runway_14R/32L                                                                   0.0
runway_18L/36R                                                                   0.0
runway_18R/36L                                                                   1.0
runway_nan                                                                       0.0
tiempo_espera_nuevo                                                           86.785
Name: 1094, dtype: object)
(1095, ICAO                                                                          39a2e3
ultimo_parado                                             2024-12-06 16:17:43.406000
despegue                                                  2024-12-06 16:19:29.679000
tiempo_espera                                                                106.273
lat                                                                        40.505699
lon                                                                        -3.559219
fecha_despegue                                                   2024-12-06 00:00:00
hora_despegue                                                                     16
aircraft_type_Heavy (larger than 136000 kg)                                      0.0
aircraft_type_High vortex aircraft                                               0.0

In [ ]:
for indice, fila in df_encoded.iterrows():
    tiempo_referencia = fila["ultimo_parado"]
    df_encoded["ventana"] = df_encoded.apply(lambda row: calcular_tiempo_relativo(tiempo_referencia,row["despegue"])

In [137]:
def calcular_tiempo_relativo(tiempo_referencia,tiempo_fila):
    return (tiempo_referencia - tiempo_fila).total_seconds()

In [131]:
calcular_tiempo_relativo(tiempo_referencia,df_encoded.loc[1,"ultimo_parado"])

21386

In [145]:
len(df_encoded)

1296

In [146]:
for indice, fila  in df_encoded.iterrows():
    if indice != len(df_encoded):
      #  tiempo_referencia = fila["ultimo_parado"]
        tiempo_referencia = fila["despegue"]
        # Seleccionar solo las filas a partir del índice
        df_encoded.loc[df_encoded.index[indice+1]:, "ventana"] = df_encoded.iloc[indice+1:].apply(
            lambda row: calcular_tiempo_relativo(tiempo_referencia, row["despegue"]), axis=1)
        
        # Filtrar el DataFrame en función de la columna 'ventana'
        df_filter = df_encoded[(df_encoded["ventana"] <= 500) & (df_encoded["ventana"] != 0)]

IndexError: index 1296 is out of bounds for axis 0 with size 1296

In [147]:
for indice, fila in df_encoded.iterrows():
    if indice < len(df_encoded) - 1:  # Verificar que no sea el último índice
        tiempo_referencia = fila["despegue"]
        
        # Seleccionar solo las filas a partir del índice
        df_encoded.loc[df_encoded.index[indice + 1]:, "ventana"] = df_encoded.iloc[indice + 1:].apply(
            lambda row: calcular_tiempo_relativo(tiempo_referencia, row["despegue"]), axis=1)
        
        # Filtrar el DataFrame en función de la columna 'ventana'
        df_filter = df_encoded[(df_encoded["ventana"] <= 500) & (df_encoded["ventana"] != 0)]