In [2]:
import pandas as pd

df_sc = pd.read_parquet('../../../data/scenarios/scenario_001.parquet')
df_sc.head()

,df,squawk,bds60_bds,bds60_heading,bds60_IAS,bds60_Mach,bds60_vrate_barometric,bds60_vrate_inertial,icao24,ts,...,bds21_registration,bds40_target_source,bds17_bds45,bds17_bds54,bds17_bds55,bds17_bds56,year,month,day,hour
0,20,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,3c618b,1741503722828,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2025,3,9,7
1,20,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,347256,1741503722828,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2025,3,9,7
2,17,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,3451d8,1741503722828,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2025,3,9,7
3,20,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,4952c6,1741503722828,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2025,3,9,7
4,21,5045,60,187.734375,256.0,0.724,-192.0,0.0,347256,1741503722828,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2025,3,9,7

Aqui se puede ver el despegue. ICAO: 34324e

https://globe.adsbexchange.com/?replay=2025-03-09-07:02&lat=40.483&lon=-3.546&zoom=13.5

In [3]:
df_sc['icao24'].value_counts()

icao24
44d068    1077
3c618b     968
4d2224     954
44d2aa     934
3415ce     923
          ...
3c49c9       4
346082       2
347307       1
2ebb69       1
3453cc       1
Name: count, Length: 121, dtype: Int64

In [14]:
print(pd.to_datetime(df_sc['ts'], unit='ms').min(), " - ", pd.to_datetime(df_sc['ts'], unit='ms').max())

2025-03-09 07:02:02.828000  -  2025-03-09 07:04:02.799000

In [15]:
len(df_sc.columns)

134

[12, 11, 10, 9, 8, 7, 6]

In [17]:
for c in df_sc.columns:
    print(c)

df
squawk
bds60_bds
bds60_heading
bds60_IAS
bds60_Mach
bds60_vrate_barometric
bds60_vrate_inertial
icao24
ts
bds
NACv
groundspeed
track
vrate_src
vertical_rate
geo_minus_baro
tc
NUCp
NICb
altitude
source
parity
lat_cpr
lon_cpr
lat_deg
lon_deg
bds40_bds
bds40_selected_mcp
bds40_barometric_setting
bds40_selected_fms
selected_altitude
barometric_setting
NACp
tcas_operational
bds50_bds
bds50_roll
bds50_track
bds50_groundspeed
bds50_track_rate
bds50_TAS
version
NICa
GVA
SIL
BAI
HRD
SILs
bds45_bds
bds45_turbulence
bds45_wind_shear
bds45_microburst
bds45_icing
bds45_wake_vortex
bds45_static_temperature
bds45_static_pressure
bds45_radio_height
tisb
id
wake_vortex
callsign
TAH
selected_heading
bds20_bds
bds20_callsign
subtype
emergency_state
bds05_tc
bds05_NUCp
bds05_NICb
bds05_altitude
bds05_source
bds05_parity
bds05_lat_cpr
bds05_lon_cpr
bds10_bds
bds10_config
bds10_ovc
bds10_acas
bds10_subnet
bds10_level5
bds10_mode_s
bds10_identification
bds10_squitter
bds10_sic
bds10_gicb
bds10_acas_hybrid
bds10_acas_ra
bds10_dte
bds17_bds
bds17_bds05
bds17_bds06
bds17_bds07
bds17_bds08
bds17_bds09
bds17_bds0a
bds17_bds20
bds17_bds40
bds17_bds50
bds17_bds51
bds17_bds52
bds17_bds5f
bds17_bds60
autopilot
vnav_mode
alt_hold
approach_mode
lnav_mode
bds44_bds
bds44_wind_speed
bds44_wind_direction
bds44_temperature
bds44_pressure
bds44_turbulence
bds44_humidity
bds17_bds21
bds17_bds53
TAS
heading
bds17_bds41
bds17_bds42
bds17_bds44
bds17_bds48
bds21_bds
bds21_registration
bds40_target_source
bds17_bds45
bds17_bds54
bds17_bds55
bds17_bds56
year
month
day
hour

In [6]:
df_sc.bds45_wake_vortex.unique()

<StringArray>
[<NA>, 'Nil']
Length: 2, dtype: string

In [13]:
df_sc.describe()

,bds60_heading,bds60_IAS,bds60_Mach,bds60_vrate_barometric,bds60_vrate_inertial,ts,NACv,groundspeed,track,vertical_rate,...,bds10_subnet,bds10_dte,bds44_wind_speed,bds44_wind_direction,bds44_temperature,bds44_pressure,bds44_turbulence,bds44_humidity,TAS,heading
count,7055.000000,6913.000000,6920.000000,7013.000000,7060.000000,48028.0,7789.000000,10070.000000,9892.000000,7789.000000,...,418.000000,418.0,0.0,0.0,54.0,0.0,0.0,0.0,0.0,0.0
mean,161.818289,246.857949,0.720103,136.519036,176.090652,1741503782422.528564,1.113750,317.700729,160.851877,221.144691,...,4.868421,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
std,92.504261,44.986090,0.150808,815.883035,879.922041,34509.254679,0.439045,176.732449,93.757672,972.764919,...,0.801323,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
min,0.000000,1.000000,0.004000,-3232.000000,-2624.000000,1741503722828.0,0.000000,0.000000,0.000000,-2624.000000,...,0.000000,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
25%,61.171875,240.000000,0.752000,-96.000000,0.000000,1741503752628.25,1.000000,226.814903,72.024633,-64.000000,...,5.000000,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
50%,201.093750,249.000000,0.768000,0.000000,0.000000,1741503782075.5,1.000000,412.408778,191.148675,0.000000,...,5.000000,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
75%,223.769531,260.000000,0.780000,128.000000,32.000000,1741503812087.0,1.000000,434.412246,220.887771,64.000000,...,5.000000,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
max,359.648438,493.000000,0.880000,4416.000000,5248.000000,1741503842799.0,2.000000,521.524688,357.187500,4352.000000,...,5.000000,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN

In [14]:
selected_columns = [
    "df",
    "icao24",
    "ts",
    "groundspeed",
    "vertical_rate",
    "altitude",
    "source",
    "lat_deg",
    "lon_deg",
    "tcas_operational",
    "version",
    "tisb",
    "wake_vortex",
    "subtype",
    "vnav_mode",
    "alt_hold",
    "approach_mode",
    "lnav_mode",
    "TAS",
    "heading"
]

df_sc[df_sc.df == '17'][selected_columns]

,df,icao24,ts,groundspeed,vertical_rate,altitude,source,lat_deg,lon_deg,tcas_operational,version,tisb,wake_vortex,subtype,vnav_mode,alt_hold,approach_mode,lnav_mode,TAS,heading
2,17,3451d8,1741503722828,NaN,NaN,9100.0,barometric,40.766235,-3.148132,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
6,17,4403bb,1741503722828,NaN,NaN,NaN,MCP/FCU,NaN,NaN,True,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
7,17,440cc1,1741503722828,NaN,NaN,38000.0,barometric,41.839600,-4.887293,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
8,17,44cdd0,1741503722828,NaN,NaN,NaN,MCP/FCU,NaN,NaN,True,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
11,17,7816b3,1741503722828,5.000000,NaN,NaN,<NA>,40.488308,-3.580529,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48015,17,344449,1741503842591,NaN,NaN,6375.0,barometric,40.738375,-3.559882,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
48016,17,44d2aa,1741503842694,NaN,NaN,36000.0,barometric,40.605469,-3.946901,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
48017,17,020176,1741503842694,477.582454,0.0,NaN,<NA>,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
48022,17,4ca856,1741503842694,NaN,NaN,NaN,MCP/FCU,NaN,NaN,True,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN
48026,17,34134e,1741503842694,435.765992,64.0,NaN,<NA>,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN

In [15]:
import pandas as pd
df = pd.read_csv('../../salida.csv', sep=',').drop(columns=['Unnamed: 1', 'ICAO.1'])
df.despegue = pd.to_datetime(df.despegue)
filtered = df[(df.despegue.dt.year == 2025) & (df.despegue.dt.day == 1) & (df.despegue.dt.month == 1) & (df.despegue.dt.hour == 15)]
filtered = filtered[(df.despegue.dt.minute > 25) & (df.despegue.dt.minute < 29)]
filtered = filtered[filtered.holding_point == 'Y1']
filtered.sort_values(by='despegue')

/var/folders/d9/w858q_3s5xj1lvw2flnmb_jr0000gn/T/ipykernel_32002/3544987770.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  filtered = filtered[(df.despegue.dt.minute > 25) & (df.despegue.dt.minute < 29)]

Empty DataFrame
Columns: [ICAO, llegada_punto, salida_punto, despegue, tiempo_espera, aircraft_type, llegada_lon, llegada_lat, salida_lon, salida_lat, holding_point, parado, runway, fecha_despegue, hora_despegue]
Index: []

In [16]:
import pandas as pd
df = pd.read_csv('../../data/Train/train.csv', sep=';')
df.despegue = pd.to_datetime(df.despegue)
filtered = df[(df.despegue.dt.year == 2025) & (df.despegue.dt.day == 1) & (df.despegue.dt.month == 1) & (df.despegue.dt.hour == 15)]
filtered = filtered[(df.despegue.dt.minute > 25) & (df.despegue.dt.minute < 29)]
filtered = filtered[filtered.holding_point == 'Y1']
filtered.sort_values(by='despegue')

/var/folders/d9/w858q_3s5xj1lvw2flnmb_jr0000gn/T/ipykernel_32002/3283159626.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  filtered = filtered[(df.despegue.dt.minute > 25) & (df.despegue.dt.minute < 29)]

,ICAO,llegada_punto,salida_punto,despegue,tiempo_espera,aircraft_type,llegada_lon,llegada_lat,salida_lon,salida_lat,holding_point,parado,runway,fecha_despegue,hora_despegue
15,345698,2025-01-01 15:24:07.211,2025-01-01 15:25:59.416,2025-01-01 15:27:13.716,186.505,Medium 2 (between 34000 kg to 136000 kg),-3.561193,40.499411,-3.560089,40.499588,Y1,True,18L/36R,2025-01-01,15
471,3445d4,2025-01-01 15:24:44.130,2025-01-01 15:27:10.733,2025-01-01 15:28:35.313,231.183,Medium 2 (between 34000 kg to 136000 kg),-3.561209,40.499446,-3.560074,40.499588,Y1,True,18L/36R,2025-01-01,15

In [17]:
df = pd.read_csv('../../data/Train/train.csv', sep=';')
df.despegue = pd.to_datetime(df.despegue)
df[(df.ICAO == '344197') & (df.holding_point == 'K1') & (df.despegue.dt.day == 29)]

,ICAO,llegada_punto,salida_punto,despegue,tiempo_espera,aircraft_type,llegada_lon,llegada_lat,salida_lon,salida_lat,holding_point,parado,runway,fecha_despegue,hora_despegue
15798,344197,2025-01-29 15:01:12.932,2025-01-29 15:01:44.667,2025-01-29 15:01:44.667,31.735,Medium 2 (between 34000 kg to 136000 kg),-3.560866,40.495559,-3.559882,40.495559,K1,True,14L/32R,2025-01-29,15
15799,344197,2025-01-29 15:01:44.910,2025-01-29 15:01:44.910,2025-01-29 15:01:44.910,0.000,NaN,-3.559882,40.495559,-3.559882,40.495559,K1,True,14L/32R,2025-01-29,15
15800,344197,2025-01-29 15:01:48.077,2025-01-29 15:02:57.627,2025-01-29 15:04:37.003,168.926,NaN,-3.559882,40.495559,-3.559631,40.495560,K1,True,14L/32R,2025-01-29,15

In [2]:
import pandas as pd
df = pd.read_csv('../../salida.csv', sep=',')
df.despegue = pd.to_datetime(df.despegue)
df

,ICAO,Unnamed: 1,ICAO.1,llegada_punto,salida_punto,despegue,tiempo_espera,aircraft_type,llegada_lon,llegada_lat,salida_lon,salida_lat,holding_point,parado,runway,fecha_despegue,hora_despegue
0,344197,0,344197,2025-01-29 15:01:15.067,2025-01-29 15:01:27.605,2025-01-29 15:01:44.667,29.6,Medium 2 (between 34000 kg to 136000 kg),-3.560699,40.49556,-3.560028,40.49556,K1,False,14L/32R,2025-01-29,15